### ISSUE TITLE
Recent builds of buster(-slim) are missing for several architectures

### ISSUE THREAD

**Issue by wholtz** [debuerreotype/docker-debian-artifacts#173] opened 2022-09-08 17:40 UTC
The 20220822 builds of `debian:buster` and `debian:buster-slim` are missing the following architectures (which exist for earlier builds):
* arm/v5
* mips64le
* ppc64le
* s390x

**Comment by tianon** [comment] 2022-09-08 17:41
Duplicate of #170 :eyes:

**Closed by tianon** 2022-09-08 17:41 UTC
