### ISSUE TITLE
Missing ppc64le image for debian:buster

### ISSUE THREAD

**Issue by mkumatag** [debuerreotype/docker-debian-artifacts#177] opened 2022-09-21 11:15 UTC
```shell
# docker manifest inspect debian:buster
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:12da36082ea17cd91307adaf2e91bb631a3fbbf2c92f7ca9545caa91036c1043",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:94d59fccce5b8617ff43a12549c046133e0310497d742d3ad9add1755297ba69",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v7"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:cb4597c2e5b3f7d54be4927f4f27d8d84d7b1cd5ef6743d4ecd752727a7e0a07",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 529,
         "digest": "sha256:0a7a6d22e520998cd8ea3543f37f6f77777f2c506bee13c66f9a6d4abd015642",
         "platform": {
            "architecture": "386",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by tianon** [comment] 2022-09-21 12:03
Duplicate of #170, #173

**Closed by tianon** 2022-09-21 12:03 UTC
