### ISSUE TITLE
GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.

### ISSUE THREAD

**Issue by basictheprogram** [debuerreotype/docker-debian-artifacts#222] opened 2024-07-07 15:49 UTC
```
docker run --rm -it debian:bullseye /bin/bash
root@16dd38da2623:/# apt update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian-security bullseye-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by tianon** [comment] 2024-07-09 20:26
This is likely either a proxy in your environment doing effectively a man-in-the-middle attack on your traffic or seccomp (and thus a duplicate of https://github.com/debuerreotype/docker-debian-artifacts/issues/122; see also https://github.com/docker-library/official-images/issues/16829).

**Comment by tianon** [comment] 2024-07-09 20:27
To illustrate further, I cannot reproduce:

```console
$ docker run -it --rm --pull=always debian:bullseye apt-get update
bullseye: Pulling from library/debian
c1c1a7d83fb1: Pull complete 
Digest: sha256:b6b4a479a3bc1b8dfda5544f00b72aafb230bb835a43974a147b220c38df882e
Status: Downloaded newer image for debian:bullseye
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8067 kB]
Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [279 kB]
Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Fetched 8573 kB in 1s (8092 kB/s)                          
Reading package lists... Done
```

**Closed by tianon** 2024-07-09 20:27 UTC
