### ISSUE TITLE
arm32v7/debian:bullseye-slim: Clock not working

### ISSUE THREAD

**Issue by satisfied83** [debuerreotype/docker-debian-artifacts#106] opened 2020-10-30 11:43 UTC
When trying to get the current time from the running arm32v7/debian:bullseye-slim image I always get back 1970 (seconds since epoch 0)

e.g.
`pi@raspberrypi:~ $ docker run -it --rm arm32v7/debian:bullseye-slim date
Thu Jan  1 00:00:00 UTC 1970
`

Furthemore: Time doesn't change if checking seconds since epochtime
`date +%s`
the result is always 0

When i run the container in privileged mode fetching time works well.

I also checked with arm32v7/debian:buster-slim there it worked flawless.

**Comment by tianon** [comment] 2020-10-30 15:59
This is the same root cause as https://github.com/debuerreotype/docker-debian-artifacts/issues/97; bullseye is now using the 64bit time syscalls on 32bit userspace, so you need to make sure your Docker is sufficiently new and you'll need a newer libseccomp than is probably available in the stable distro you're running on the host.

**Comment by satisfied83** [comment] 2020-11-04 07:29
Hi tianon, Hi all,

i just checked on the system where date command is not working the version of docker and libseccomp2. Both components seem to be the latest ones ?
Environment A (Raspberry Pi 4): Clock not working
```
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

pi@raspberrypi:~ $ docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46
 Built:             Wed Sep 16 17:07:02 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46
  Built:            Wed Sep 16 17:00:52 2020
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
pi@raspberrypi:~ $ apt list libseccomp2
Listing... Done
libseccomp2/stable,now 2.3.3-4 armhf [installed]
```


**BUT** in Environment B it works without problems although it is an older version of docker and libseccomp2 installed

```
pi@PlayPi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

pi@PlayPi:~ $ docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:30:54 2017
 OS/Arch:      linux/arm
 Experimental: false
 
pi@PlayPi:~ $ apt list libseccomp2
oldstable, 2.3.1-2.1+deb9u1

```

**Comment by satisfied83** [comment] 2020-11-04 08:07
Just checked with the old system were everything was working fine.

After updating the package `libc-bin` system is no longer able to get date properly.

**Comment by tianon** [comment] 2020-11-04 18:03
> ... you'll need a newer libseccomp than is probably available in the stable distro you're running on the host.

Specifically:

- Docker version 19.03.9 or newer
- **libseccomp version 2.4.2 or newer**

:disappointed:

**Comment by juampe** [comment] 2020-11-15 16:13
Solved for raspbian buster with libseccomp2 2.5.0-3  with apt pinning and debian testing/unsable packages
`apt-get -y install libseccomp2/unstable`

**Comment by tianon** [comment] 2021-03-23 22:20
Closing, as this isn't something we can fix directly here (it requires host updates to libseccomp and Docker).

**Closed by tianon** 2021-03-23 22:20 UTC

**Comment by Callisto88** [comment] 2022-09-08 10:15
In case anyone is still struggling with this issue i was able to solve by upgrading from buster to bullseye. Had to install `gcc-8-base` as well.
