### ISSUE TITLE
Regression in Debian images (SIGILL, exit code 132)

### ISSUE THREAD

**Issue by p0358** [debuerreotype/docker-debian-artifacts#175] opened 2022-09-14 12:31 UTC
I am opening the issue here as well so it doesn't get lost as a comment under the PR.

Basically since this PR: https://github.com/docker-library/official-images/pull/13132 and image version `20220912`, the images are completely broken on "older" CPUs. And by older I mean in my case 4th gen Intel Core CPU which worked with all images just fine before this build.

```
root@test:~# docker run --rm debian:bullseye-20220822-slim bash -c 'echo test'
test
root@test:~# echo $?
0
root@test:~# docker run --rm debian:bullseye-20220912-slim bash -c 'echo test'
root@test:~# echo $?
132
```

Everything basing their images on these new Debian ones is crashing with exit code 132 (SIGILL, illegal instruction). My CPU supports AVX2 and SSE4.2, it does seem like the update though made these images dependent on some even newer instructions or something?

As a result right now I cannot run any Debian-based images anymore at all. I can still pull and run the Alpine ones just fine for example. I hope this matter can be looked into...

It's worth to mention that while I figures out the culprit traces back here, I think many developers will have a big headache when multiple of their containers after an upgrade just exit without printing anything, when everything worked fine just a few days ago. I hope this is a correctable oversight, as it wouldn't be okay to randomly drop CPU support without changing the major versions at least...

**Comment by tianon** [comment] 2022-09-14 15:35
Interesting -- my guess is a change somewhere in here (going to check `libc6` first since it's the most likely to be able to affect something like `echo` or `bash`):

```diff
diff --git a/debian_11-slim/rootfs.manifest b/debian_11-slim/rootfs.manifest
index 24a734e..dc826fc 100644
--- a/debian_11-slim/rootfs.manifest
+++ b/debian_11-slim/rootfs.manifest
@@ -1,6 +1,6 @@
 adduser	3.118
 apt	2.2.4
-base-files	11.1+deb11u4
+base-files	11.1+deb11u5
 base-passwd	3.5.51
 bash	5.1-2+deb11u1
 bsdutils	1:2.36.1-8+deb11u1
@@ -10,7 +10,7 @@ debconf	1.5.77
 debian-archive-keyring	2021.1.1
 debianutils	4.11.2
 diffutils	1:3.7-5
-dpkg	1.20.11
+dpkg	1.20.12
 e2fsprogs	1.46.2-2
 findutils	4.8.0-1
 gcc-10-base:amd64	10.2.1-6
@@ -27,8 +27,8 @@ libaudit-common	1:3.0-2
 libaudit1:amd64	1:3.0-2
 libblkid1:amd64	2.36.1-8+deb11u1
 libbz2-1.0:amd64	1.0.8-4
-libc-bin	2.31-13+deb11u3
-libc6:amd64	2.31-13+deb11u3
+libc-bin	2.31-13+deb11u4
+libc6:amd64	2.31-13+deb11u4
 libcap-ng0:amd64	0.7.9-2.2+b1
 libcom-err2:amd64	1.46.2-2
 libcrypt1:amd64	1:4.4.18-4
@@ -41,13 +41,13 @@ libgcrypt20:amd64	1.8.7-6
 libgmp10:amd64	2:6.2.1+dfsg-1+deb11u1
 libgnutls30:amd64	3.7.1-5+deb11u2
 libgpg-error0:amd64	1.38-2
-libgssapi-krb5-2:amd64	1.18.3-6+deb11u1
+libgssapi-krb5-2:amd64	1.18.3-6+deb11u2
 libhogweed6:amd64	3.7.3-1
 libidn2-0:amd64	2.3.0-5
-libk5crypto3:amd64	1.18.3-6+deb11u1
+libk5crypto3:amd64	1.18.3-6+deb11u2
 libkeyutils1:amd64	1.6.1-2
-libkrb5-3:amd64	1.18.3-6+deb11u1
-libkrb5support0:amd64	1.18.3-6+deb11u1
+libkrb5-3:amd64	1.18.3-6+deb11u2
+libkrb5support0:amd64	1.18.3-6+deb11u2
 liblz4-1:amd64	1.9.3-2
 liblzma5:amd64	5.2.5-2.1~deb11u1
 libmount1:amd64	2.36.1-8+deb11u1
@@ -58,7 +58,7 @@ libpam-modules:amd64	1.4.0-9+deb11u1
 libpam-modules-bin	1.4.0-9+deb11u1
 libpam-runtime	1.4.0-9+deb11u1
 libpam0g:amd64	1.4.0-9+deb11u1
-libpcre2-8-0:amd64	10.36-2
+libpcre2-8-0:amd64	10.36-2+deb11u1
 libpcre3:amd64	2:8.39-13
 libseccomp2:amd64	2.5.1-1+deb11u1
 libselinux1:amd64	3.1-3
@@ -69,12 +69,12 @@ libsmartcols1:amd64	2.36.1-8+deb11u1
 libss2:amd64	1.46.2-2
 libssl1.1:amd64	1.1.1n-0+deb11u3
 libstdc++6:amd64	10.2.1-6
-libsystemd0:amd64	247.3-7
+libsystemd0:amd64	247.3-7+deb11u1
 libtasn1-6:amd64	4.16.0-2
 libtinfo6:amd64	6.2+20201114-2
 libtirpc-common	1.3.1-1+deb11u1
 libtirpc3:amd64	1.3.1-1+deb11u1
-libudev1:amd64	247.3-7
+libudev1:amd64	247.3-7+deb11u1
 libunistring2:amd64	0.9.10-4
 libuuid1:amd64	2.36.1-8+deb11u1
 libxxhash0:amd64	0.8.0-2
@@ -93,4 +93,4 @@ sysvinit-utils	2.96-7+deb11u1
 tar	1.34+dfsg-1
 tzdata	2021a-1+deb11u5
 util-linux	2.36.1-8+deb11u1
-zlib1g:amd64	1:1.2.11.dfsg-2+deb11u1
+zlib1g:amd64	1:1.2.11.dfsg-2+deb11u2
```

I don't think I've got any systems where I can reproduce, but can you reproduce with a simpler command that doesn't involve `bash` too, like just `echo test` directly?

**Comment by tianon** [comment] 2022-09-14 15:37
https://tracker.debian.org/news/1358014/accepted-glibc-231-13deb11u4-source-into-proposed-updates-stable-new-proposed-updates/ has a lot of relevant-sounding changes in it :grimacing:

**Comment by p0358** [comment] 2022-09-14 16:31
Interestingly running just `docker run --rm debian:bullseye-20220912-slim echo test` works, but running `docker run --rm debian:bullseye-20220912-slim bash` yields the 132 exit code.

Testing a few random commands:

Broken:
- bash
- su

Works:
- uname
- echo
- cp
- mkdir
- sh

By "broken" I consider exiting immediately with 132 exit code and no output or functionality, but "works" I consider functioning as usual at first glance.

Making matters worse, the command mentioned earlier `bash -c 'echo test'` happens to work on my 1st gen Intel Core system (with no AVX support at all).

So for full disclosure, the precise CPU on which it's broken is Intel Core i3-4000M (one that appears to be of the very first generation to support AVX2). I wonder if this could be some microcode bug in earlier implementations that was accidentally triggered with this update then...

**Comment by tianon** [comment] 2022-09-14 16:37
Yeah, I guess it would be useful if you could somehow get an `strace` or even attach `gdb` on it -- my guess is still that it's a bug in glibc (given the changes above) and likely something the package maintainers would probably appreciate being aware of. :grimacing:

If you manage to get a trace of some kind on it though, that could help confirm where the failure is.

Given `sh` appears to work, I think the easiest way would probably be something like `docker run -it --rm --name test debian:bullseye sh` in one terminal, `docker top test` in another to get the host PID, then run `strace` from your host attached to that PID (in "follow" mode so it captures children) and then return to `sh` and invoke `bash` (or similar command that SIGILLs).

**Comment by p0358** [comment] 2022-09-14 19:24
```
Fetched 20.5 MB in 2s (9818 kB/s)
Reading changelogs... Done
Preconfiguring packages ...
(Reading database ... 21422 files and directories currently installed.)
Preparing to unpack .../libc6_2.31-13+deb11u4_amd64.deb ...
Unpacking libc6:amd64 (2.31-13+deb11u4) over (2.31-13+deb11u3) ...
E: Sub-process /usr/bin/dpkg exited unexpectedly
root@test:~# passwd
Illegal instruction
root@test:~#
```
Oh no, now my host got corrupted too xDDD Well at least that confirms it's not an issue with Docker and container explicitly, but with this Debian update... (thankfully this is just an LXC container and I didn't update the mother host). And I guess that it's an issue with `libc6` because it bailed out right after doing this update.

Now that I think about it, I recall two events:
- bun.js runtime statically compiled also gave "Illegal instruction", but many people had this, however looking back at this, they all had CPUs without AVX (v1) instructions, while mine should support AVX2, I shrugged it off that they must have supported
- after installing Linux on that machine I do recall I had some warning about microcode bug, but I also ignored it assuming it had to do something with UEFI, so that may or may not be related

I'll try to fix this container and give updates on strace as soon as I manage to run it, I've also read about read about `noxsave` option in kernel that as a side effects disables AVX, so I'll probably see if that works for me, plus I'll reboot to try catching that microcode warning in kernel log perhaps

What I can tell so far is these lines from kernel.log (on host):
```
Sep 14 21:12:09 G510 kernel: [834669.721253] traps: dpkg[1455373] trap invalid opcode ip:7fa39701951d sp:7ffc4ad26e58 error:0 in libc-2.31.so[7fa396edd000+15a000]
Sep 14 21:12:09 G510 kernel: [834669.732958] traps: dpkg[1455374] trap invalid opcode ip:7f529ca9551d sp:7fffb6f0a238 error:0 in libc-2.31.so[7f529c959000+15a000]
Sep 14 21:12:09 G510 kernel: [834669.840128] traps: dpkg[1455375] trap invalid opcode ip:7f1874cc951d sp:7fffc2c2f5d8 error:0 in libc-2.31.so[7f1874b8d000+15a000]
Sep 14 21:12:09 G510 kernel: [834669.907918] traps: dpkg[1455378] trap invalid opcode ip:7f3b4f8d851d sp:7fff3ec970f8 error:0 in libc-2.31.so[7f3b4f79c000+15a000]
Sep 14 21:12:51 G510 kernel: [834712.152139] traps: passwd[1455693] trap invalid opcode ip:7fefee4b52b7 sp:7ffffcb506b8 error:0 in libc-2.31.so[7fefee37d000+15a000]
```
I don't know much about debugging on Linux, so unsure if `+15a000` is relative address inside of the .so? If not then the address itself is probably not that useful

**Comment by p0358** [comment] 2022-09-14 19:53
Relevant strace fragment:
```
access("/usr/bin/bash", R_OK)           = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
rt_sigprocmask(SIG_BLOCK, [INT TERM CHLD], [], 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f4540604d60}, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f4540604d60}, 8) = 0
pipe([3, 4])                            = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f45405c6a10) = 2785
rt_sigaction(SIGTERM, {sa_handler=SIG_IGN, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f4540604d60}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f4540604d60}, 8) = 0
setpgid(2785, 2785)                     = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
close(3)                                = 0
close(4)                                = 0
ioctl(255, TIOCGPGRP, [2785])           = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
wait4(-1, [{WIFSIGNALED(s) && WTERMSIG(s) == SIGILL}], WSTOPPED|WCONTINUED, NULL) = 2785
rt_sigprocmask(SIG_BLOCK, [CHLD TSTP TTIN TTOU], [CHLD], 8) = 0
ioctl(255, TIOCSPGRP, [482])            = 0
rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
ioctl(255, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(255, SNDCTL_TMR_STOP or TCSETSW, {B38400 opost isig icanon echo ...}) = 0
ioctl(255, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(255, TIOCGWINSZ, {ws_row=37, ws_col=120, ws_xpixel=0, ws_ypixel=0}) = 0
write(2, "Illegal instruction\n", 20)   = 20
```

**Comment by p0358** [comment] 2022-09-14 20:29
Core dump of bash (although I didn't have success loading it in GDB, it seems `bash` was stripped of debugging symbols potentially): [core.bash.100000.2663c40e671041e6b40c882a70b83c3f.1480736.1663185824000000.zip](https://github.com/debuerreotype/docker-debian-artifacts/files/9569748/core.bash.100000.2663c40e671041e6b40c882a70b83c3f.1480736.1663185824000000.zip)

**Comment by p0358** [comment] 2022-09-14 20:35
Going to 0x15a000 in IDA:
![obraz](https://user-images.githubusercontent.com/5182588/190256853-29ae80aa-0089-4da2-a430-990e2693d15c.png)

Looks like these instructions are indeed related to AVX at least, though I know nothing about them tbh

**Comment by p0358** [comment] 2022-09-14 20:44
While I have no symbols, my assumption about strncmp is that this fragment where it gets that function and calls it
![obraz](https://user-images.githubusercontent.com/5182588/190258324-ad101d04-5faa-467a-ad1f-5143876cf2a0.png)
might be the equivalent of this: https://github.com/bminor/glibc/blob/ac8047cdf326504f652f7db97ec96c0e0cee052f/sysdeps/x86_64/multiarch/strncmp.c#L55

I have no idea though how to get symbols or report the Debian bug. If this thing indeed is checking for AVX capabilities, then probably some workaround with shadowing/disabling them in the kernel would work, but it'd be ideal if the authors found the root cause of this probably...

**Comment by tianon** [comment] 2022-09-14 20:49
`in libc-2.31.so` is the key (if it wasn't already confirmed by your package upgrade :see_no_evil: :heart:)

I'd suggest that if you can get `reportbug` working, it's probably the best way to report this bug (`reportbug libc6`, I think).  It should walk you through the steps. :+1:

(If you can't get it working in the now-upgraded environment, then doing so on the host is probably a good alternative since it'll have the same CPU and run into the same bug after upgrade.)

**Comment by p0358** [comment] 2022-09-15 01:04
For future reference, I've reported the bug here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1019855

Also the kernel option `clearcpuid=293` hid `avx2` from `/proc/cpuinfo`, but didn't fix those crashes. They also occur with a Fedora Docker image, so it's likely upstream libc issue, I hope the Debian maintainers will forward it where appropriate...

**Comment by tianon** [comment] 2022-09-16 22:34
I'm going to close this in favor of that (very productive looking :eyes:) Debian bug. :+1:

**Closed by tianon** 2022-09-16 22:34 UTC
