### ISSUE TITLE
debian/debian-slim container image not using latest Linux kernel version(s)

### ISSUE THREAD

**Issue by tommyreilly** [debuerreotype/docker-debian-artifacts#145] opened 2021-11-12 19:03 UTC
When scanning the latest debian-slim 11 (bullseye), we are finding a high number of Linux Kernel high/critical CVEs with CVSS v3 score > 7 being flagged.

On inspection, the scanning tool we are using is flagging anything using a Linux Kernel version earlier than v5.10.70>

Doing a "uname -r" within a shell of he debian/debian-slim images, it indicates that 5.10.47-linuxkit is the Linux Kernel version being used.

```
docker run -it docker.io/debian:latest /bin/bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
bb7d5a84853b: Already exists 
Digest: sha256:4d6ab716de467aad58e91b1b720f0badd7478847ec7a18f66027d0f8a329a43c
Status: Downloaded newer image for debian:latest
root@c4629442dd5c:/# uname -r
5.10.47-linuxkit
root@c4629442dd5c:/# exit
```

Are there any plans to update the kernel version to prevent these high/critical CVEs from being flagged?

Thanks

Tommy

**Comment by tianon** [comment] 2021-11-12 19:14
Duplicate of #144

There is no kernel in these Docker images -- the kernel version you see when you run `uname -r` is the kernel of your host.

**Closed by tianon** 2021-11-12 19:14 UTC

**Comment by tommyreilly** [comment] 2021-11-13 16:54
Understood - thanks @tianon
