### ISSUE TITLE
/usr/share/man/man1 directory should be preserved

### ISSUE THREAD

**Issue by Yannik** [debuerreotype/docker-debian-artifacts#89] opened 2020-04-03 13:45 UTC
Installing the openjdk-11-jre-headless package on buster-slim fails with the following error:

```
update-alternatives: error: error creating symbolic link '/usr/share/man/man1/rm
id.1.gz.dpkg-tmp': No such file or directory
dpkg: error processing package openjdk-11-jre-headless:amd64 (--configure):
 installed openjdk-11-jre-headless:amd64 package post-installation script subpro
cess returned error exit status 2
```
 This is due to the `'/usr/share/man/man1/` directory being removed in `buster-slim`.

I suggest to keep the directory but remove the actual man files to fix this.

**Comment by tianon** [comment] 2020-04-03 17:49
Duplicate of #24, #25, #42, #46, #64, and thus https://github.com/debuerreotype/debuerreotype/issues/10.

**Closed by tianon** 2020-04-03 17:49 UTC
