### ISSUE TITLE
SIGTERM not properly stopping the container starting from bullseye

### ISSUE THREAD

**Issue by jeroenj** [debuerreotype/docker-debian-artifacts#176] opened 2022-09-16 12:31 UTC
We're having an issue where containers based on Debian Bullseye to no longer being able to be stopped cleanly.

This can be reproduced by starting the container locally:

```sh
docker run --name test --rm -it debian:bullseye bash
```

And then stopping it from a new process:

```sh
docker stop --time 8 test
```

You'll notice that it takes 8 seconds to stop the container.

This is also being logged by the docker daemon:

```
Container failed to exit within 15s of signal 15 - using the force
```

This issue is not present on the (latest) Buster images.

I was able to pinpoint the issue to a specific tag where the issue was introduced. `debian:bullseye-20201012` does not have the issue, but `debian:bullseye-20201117` does.

We can reproduce this on various recent Docker (20.10.18) and containerd (1.5.13, on GKE 1.22) installations.

**Comment by tianon** [comment] 2022-09-16 17:30
I did some testing with tags of https://hub.docker.com/_/bash (because this is definitely a Bash change/bug, not really a Debian issue), and the results were kind of interesting.  It fails on Bash 3.2, 4.0, 4.1, and 4.2, then works on 4.3, 4.4, 5.0, and finally starts failing again on 5.1, so something changed between Bash 5.0 and 5.1 (which is consistent with Debian Buster having Bash 5.0 and Bullseye having 5.1).

I would suggest the best place to discuss this further is probably the Bash bugs mailing list (maybe it was an intentional change?).  It probably only affects Bash running as PID 1. :grimacing:

(FWIW, I can still reproduce with `bash:devel` which is currently built from https://git.savannah.gnu.org/cgit/bash.git/commit/?h=devel&id=b7b9d7c306b2881560c4f94b7e7c7175f851c891 at the tip of the `devel` branch)

I bet adding something like `trap 'exit' TERM` to the Bash session "fixes" it (in a more explicit way than the previous implicit behavior). :sweat_smile:

**Comment by tianon** [comment] 2022-09-16 17:32
FWIW, here's the (very rough, raw) script I used to test:

<details>
<summary>Test Script:</summary>

```bash
#!/usr/bin/env bash
set -Eeuo pipefail

versions=(
	# https://hub.docker.com/_/bash/tags
	3.2
	4.0
	4.1
	4.2
	4.3
	4.4
	5.0-beta
	5.0-beta2
	5.0-rc1
	5.0
	5.1-alpha
	5.1-beta
	5.1-rc1
	5.1-rc2
	5.1-rc3
	5.1
	5.2-alpha
	5.2-beta
	5.2-rc1
	5.2-rc2
	5.2-rc3
	5.2-rc4
	devel
)

for version in "${versions[@]}"; do
	name="test-bash-$version"
	docker pull --quiet "bash:$version"
	docker run --name "$name" -itd "bash:$version"
	docker kill -sTERM "$name"
	sleep 1 # give it a second to die
	stat="$(docker container inspect --format '{{ .State.Status }}' "$name")"
	if [ "$stat" = 'running' ]; then
		echo "$version: fail"
	fi
	docker rm -vf "$name"
done
```

</details>

**Comment by jeroenj** [comment] 2022-09-19 14:57
Thanks a lot for this research!

`trap 'exit' TERM` seems like a sensible workaround indeed. 😅

I guess the main issue is that our entrypoint script is a bash script. Having some kind of basic init system in front of it would probably mitigate this issue as well.

I'll experiment a bit with our setup and report back here. I guess this issue can be closed now since it's not really related to Debian. That said I do think this _change_ in bash feels like a regression to me. 😅

**Comment by robsonpeixoto** [comment] 2022-12-19 11:53
Try to avoid use bash as PID and use `exec ...` on your last command. 
For example:
- https://github.com/docker-library/postgres/blob/75d0c1135e1cfd183bf7ee0970b7031986b0710d/15/bullseye/docker-entrypoint.sh#L341
- https://github.com/docker-library/postgres/blob/75d0c1135e1cfd183bf7ee0970b7031986b0710d/15/bullseye/Dockerfile#L189

Another possible solution is use `tini`: https://github.com/krallin/tini

**Comment by tianon** [comment] 2022-12-19 16:06
(Thanks for the reminder; I'm going to close this now :sweat_smile:)

**Closed by tianon** 2022-12-19 16:06 UTC
