### ISSUE TITLE
Debian 10 buster released

### ISSUE THREAD

**Issue by tao12345666333** [debuerreotype/docker-debian-artifacts#76] opened 2019-07-07 08:02 UTC
Debian 10 buster released. https://www.debian.org/News/2019/20190706

https://www.debian.org/releases/buster/index.en.html

Should we add `bullseye` tag ?

**Comment by jsf9k** [comment] 2019-07-08 20:11
It would be great if new buster images were released as well.  Right now updating with the existing buster images require some extra sauce because of errors like this:
```console
Repository 'http://security-cdn.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'testing' to 'stable'
```

**Comment by MarcoFalke** [comment] 2019-07-08 20:18
Looks like the `debian:10` and `debian:11` tags are missing as well.

**Comment by tianon** [comment] 2019-07-08 22:46
Builds are in progress -- we have a large matrix (all supported suites multiplied by all supported architectures), so it takes a bit.  We're also contending with https://lists.debian.org/debian-stable-announce/2019/07/msg00000.html to some extent which is an additional wrinkle (otherwise I likely would've had builds started this morning and be looking to collect them into Git already).

Suffice to say builds are in progress and I'll be getting them out ASAP.  They should definitely include a `debian:10` alias (since that's officially released) but will not likely include `debian:11` since that is not officially released (same as every previous testing we've had).

Regarding build failures with the current buster images, I'm not able to reproduce:

```console
$ docker pull debian:buster
buster: Pulling from library/debian
Digest: sha256:543a3f93a1f53d2d292ec067fa13528d5f3843ae4c4ffe6ef6993ca70b6ac2fa
Status: Image is up to date for debian:buster

$ docker run --rm debian:buster bash -eux -c 'apt-get update && apt-get install -y vim'
+ apt-get update
Get:1 http://cdn-fastly.deb.debian.org/debian buster InRelease [118 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:3 http://security-cdn.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Get:5 http://security-cdn.debian.org/debian-security buster/updates/main amd64 Packages [1864 B]
Fetched 8103 kB in 1s (8338 kB/s)
Reading package lists...
+ apt-get install -y vim
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libgpm2 vim-common vim-runtime xxd
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime xxd
0 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
Need to get 7425 kB of archives.
After this operation, 33.8 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 xxd amd64 2:8.1.0875-5 [140 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 vim-common all 2:8.1.0875-5 [195 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libgpm2 amd64 1.20.7-5 [35.1 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 vim-runtime all 2:8.1.0875-5 [5775 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 vim amd64 2:8.1.0875-5 [1280 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 7425 kB in 0s (138 MB/s)
Selecting previously unselected package xxd.
(Reading database ... 6674 files and directories currently installed.)
Preparing to unpack .../xxd_2%3a8.1.0875-5_amd64.deb ...
Unpacking xxd (2:8.1.0875-5) ...
Selecting previously unselected package vim-common.
Preparing to unpack .../vim-common_2%3a8.1.0875-5_all.deb ...
Unpacking vim-common (2:8.1.0875-5) ...
Selecting previously unselected package libgpm2:amd64.
Preparing to unpack .../libgpm2_1.20.7-5_amd64.deb ...
Unpacking libgpm2:amd64 (1.20.7-5) ...
Selecting previously unselected package vim-runtime.
Preparing to unpack .../vim-runtime_2%3a8.1.0875-5_all.deb ...
Adding 'diversion of /usr/share/vim/vim81/doc/help.txt to /usr/share/vim/vim81/doc/help.txt.vim-tiny by vim-runtime'
Adding 'diversion of /usr/share/vim/vim81/doc/tags to /usr/share/vim/vim81/doc/tags.vim-tiny by vim-runtime'
Unpacking vim-runtime (2:8.1.0875-5) ...
Selecting previously unselected package vim.
Preparing to unpack .../vim_2%3a8.1.0875-5_amd64.deb ...
Unpacking vim (2:8.1.0875-5) ...
Setting up libgpm2:amd64 (1.20.7-5) ...
Setting up xxd (2:8.1.0875-5) ...
Setting up vim-common (2:8.1.0875-5) ...
Setting up vim-runtime (2:8.1.0875-5) ...
Setting up vim (2:8.1.0875-5) ...
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
Processing triggers for libc-bin (2.28-10) ...
```

**Comment by jsf9k** [comment] 2019-07-09 12:31
> Regarding build failures with the current buster images, I'm not able to reproduce:

You're right, that was an error on my end.  Thanks for pointing me in the right direction.

**Comment by tianon** [comment] 2019-07-09 14:33
Once https://github.com/docker-library/official-images/pull/6251 merges, this will be updated.  (So any work in this repository is now complete and as such I'm closing this in favor of that PR. :+1:)

**Closed by tianon** 2019-07-09 14:33 UTC
