### ISSUE TITLE
GPG error: At least one invalid signature was encountered. (debian:bullseye)

### ISSUE THREAD

**Issue by OBerghmans** [debuerreotype/docker-debian-artifacts#101] opened 2020-08-07 17:44 UTC
Hi,

Starting from few days ago, with the new image, I get the following error when using the debian:bullseye images:

```
$ docker run --rm --cap-add=NET_ADMIN -it debian:bullseye
Unable to find image 'debian:bullseye' locally
bullseye: Pulling from library/debian
984ab044320f: Pull complete
Digest: sha256:453a6ee850e6eafb3c237c48cebcbf94b233656d64c3e73bd167b2775fab5dba
Status: Downloaded newer image for debian:bullseye
root@4b8a01a9c819:/# apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I'm running this on my Raspberry Pi 4, using Raspbian. Is this something client side, or did a change in the docker image cause this?

Krgds,
Olivier

**Comment by tianon** [comment] 2020-08-07 17:55
Unfortunately, this sounds like it's the same root cause as https://github.com/debuerreotype/docker-debian-artifacts/issues/97 -- your Raspberry Pi 4 is probably running an arm64 kernel, but the `debian:bullseye` image is arm32 (arm32v7 / armhf).

To fix this, you'll need to make sure your Docker version is newer than 19.03.9, and that you have a libseccomp version of 2.4.2 or higher (which isn't available in either `buster` or `buster-backports` right now, unfortunately).

**Comment by OBerghmans** [comment] 2020-08-07 18:15
Thanks for the quick reply!
I'm not using the 64 bit image yet, so my raspberry pi is running the armv71 kernel of raspbian buster:

```
# uname -a
Linux RU-Pi4 5.4.51-v7l+ #1332 SMP Tue Aug 4 18:40:14 BST 2020 armv7l GNU/Linux
```

Furthermore, everything should be on the latest version as I did an `apt full-upgrade` earlier this week. The docker version is on 19.03.12:

```
$ docker --version
Docker version 19.03.12, build 48a6621
```

By the way, the bullseye image was working earlier this week, but since the new one it started giving those GPG errors.

**Comment by tianon** [comment] 2020-08-07 19:06
Right, the image update this week took `libc6` from 2.30 to 2.31:

https://github.com/debuerreotype/docker-debian-artifacts/compare/c3f811dd6b0d8e37bf524c78d0bfc8ed4a59ada9..3503997cf522377bc4e4967c7f0fcbcb18c69fc8#diff-5ce6033390241f41c37e3028f55d1ec7

```diff
-libc-bin	2.30-8
+libc-bin	2.31-2
```

I guess this affects not just 32bit architectures on a 64bit kernel, but also 32bit architectures on a sufficiently new kernel. :disappointed:

So you still need newer `libseccomp` to fix this (which unfortunately isn't available in either `buster` or even `buster-backports` right now) -- your Docker is new enough, but without the newer `libseccomp`, Docker can't whitelist the newer 64bit time-related system calls, so many basic operations in the image will fail (for example, even just `sleep 1` is enough to reproduce, since it will now use the 64bit versions of the clock-related system calls).

**Comment by OBerghmans** [comment] 2020-08-14 21:26
Ok, thanks for the information!
Shall I close the issue?

**Comment by tianon** [comment] 2020-08-15 00:13
Yeah, I think that makes sense (since there's not anything we can change at this level to "fix" this, and it's really something that has to be fixed on the host). :heart:

**Closed by tianon** 2020-08-15 00:13 UTC

**Comment by vlasov01** [comment] 2021-11-28 14:12
The solution for me  to update libseccomp2 was:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo 'deb http://httpredir.debian.org/debian buster-backports main contrib non-free' | sudo tee -a /etc/apt/sources.list.d/debian-backports.list
sudo apt update && sudo apt upgrade -y
sudo apt install libseccomp2 -t buster-backports
```

**Comment by miholeus** [comment] 2022-01-07 18:37
@vlasov01 thanks, it works!
